Checks 5

diff --git a/.github/workflows/pr-development-stage.yml b/.github/workflows/pr-development-stage.yml
--- a/.github/workflows/pr-development-stage.yml
+++ b/.github/workflows/pr-development-stage.yml
@@ -187,3 +187,18 @@ jobs:
           exit 1  # Simulate test failure for demonstration
         continue-on-error: true
 #        if: always()
+
+  test-job:
+    name: Test Job
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+
+    steps:
+      # Tests
+      - name: Tests
+        run: |
+          echo "Failure in 2nd JOB - NO continue-on-error: true..."
+          exit 1  # Simulate test failure for demonstration
+#        continue-on-error: true
+#       if: always()
